name: DeliciousFoodMap

services:
  mysql:
    image: mysql:8.0
    expose:
      - 3306
    networks:
      - private-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=delicious_food_map
    volumes:
      # 卷映射，需要在顶级元素声明
      - mysql-data:/var/lib/mysql
      - ./sql/delicious-food-map.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  redis:
    image: redis:latest
    environment:
      - REDIS_PASSWORD=123456
    expose:
      - 6379
    networks:
      - private-network
    restart: always
    volumes:
      - redis-data:/redis/data
      - redis-conf:/usr/local/etc/redis/redis.conf

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - private-network
    volumes:
      - backend:/app/logs
    restart: always
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
  redis-data:
  redis-conf:
  backend:

networks:
  private-network: