name: deliciousfoodmap

services:
  mysql:
    container_name: deliciousfoodmap-mysql
    image: mysql:8.0
    expose:
      - 3306
    networks:
      - private-network
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=delicious-food-map
    volumes:
      # 卷映射，需要在顶级元素声明
      - mysql-data:/var/lib/mysql
      - ./sql/delicious-food-map.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  redis:
    container_name: deliciousfoodmap-redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=123456
    expose:
      - 6379
    networks:
      - private-network
    restart: always
    volumes:
      - redis-data:/data

  backend:
    container_name: deliciousfoodmap-backend
    image: dhbxs/delicious-food-map-admin:latest
    expose:
      - 8081
    networks:
      - private-network
    volumes:
      - backend:/app/logs
    restart: always
    depends_on:
      - mysql
      - redis

  frontend:
    container_name: deliciousfoodmap-frontend
    image: dhbxs/delicious-food-map-web:latest
    ports:
      - "8080:80"
    environment:
      - APP_AMAP_KEY={your amap key}
      - APP_BACKEND_URL={your backend url}
    networks:
      - private-network
    restart: always
    depends_on:
      -  backend

volumes:
  mysql-data:
  redis-data:
  redis-conf:
  backend:

networks:
  private-network: